import { 
  ArrowLeft, 
  MapPin, 
  Navigation, 
  Clock, 
  Fuel, 
  Truck, 
  User, 
  FileText, 
  Paperclip, 
  Package,
  CheckCircle2,
  Circle,
  AlertTriangle,
  Send
} from "lucide-react";
import { motion } from "framer-motion";

export default function TripDetails({ trip, onBack }) {

  const timelineEvents = [
    { id: 1, label: "Trip Created", detail: "Dispatch order generated by fleet manager", time: "8:00 AM", status: "completed", icon: FileText },
    { id: 2, label: "Vehicle Loaded", detail: `${trip.cargoType || "Cargo"} loaded onto ${trip.vehicle}`, time: "9:15 AM", status: "completed", icon: Package },
    { id: 3, label: "Dispatched from Origin", detail: `Departed from ${trip.source}`, time: new Date(trip.startTime).toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" }), status: "completed", icon: Send },
    { id: 4, label: "In Transit", detail: `En route to ${trip.destination} — ${trip.distance} mi total`, time: "Current", status: trip.status === "Completed" ? "completed" : trip.status === "Cancelled" ? "cancelled" : "active", icon: Navigation },
    ...(trip.status === "Delayed" ? [{ id: 5, label: "Delay Reported", detail: "Weather / traffic delay reported by driver", time: "—", status: "warning", icon: AlertTriangle }] : []),
    { id: 6, label: "Arrival at Destination", detail: `Delivery at ${trip.destination}`, time: trip.eta, status: trip.status === "Completed" ? "completed" : "pending", icon: MapPin },
    { id: 7, label: "Trip Completed", detail: "Proof of delivery submitted", time: trip.status === "Completed" ? trip.eta : "Pending", status: trip.status === "Completed" ? "completed" : "pending", icon: CheckCircle2 }
  ];

  // Compute progress from status
  const progressMap = { "Scheduled": 5, "In Progress": 55, "Delayed": 42, "Completed": 100, "Cancelled": 0 };
  const progress = progressMap[trip.status] ?? 0;

  const fuelEstimate = {
    rate: trip.distance > 500 ? "6.5 mpg" : "18.2 mpg",
    estimated: trip.distance > 500 ? Math.ceil(trip.distance / 6.5) : Math.ceil(trip.distance / 18.2),
    cost: trip.distance > 500 ? Math.ceil((trip.distance / 6.5) * 3.65) : Math.ceil((trip.distance / 18.2) * 3.65)
  };

  const getTimelineIcon = (status) => {
    switch (status) {
      case "completed":
        return "bg-emerald-500 text-white border-emerald-500";
      case "active":
        return "bg-blue-500 text-white border-blue-500 animate-pulse";
      case "warning":
        return "bg-amber-500 text-white border-amber-500";
      case "cancelled":
        return "bg-rose-500 text-white border-rose-500";
      default:
        return "bg-slate-200 dark:bg-slate-800 text-slate-400 dark:text-slate-600 border-slate-300 dark:border-slate-700";
    }
  };

  const getStatusColor = (status) => {
    switch (status) {
      case "Completed": return "text-emerald-600 bg-emerald-50 dark:bg-emerald-950/20 dark:text-emerald-400 border-emerald-200/50 dark:border-emerald-800/30";
      case "In Progress": return "text-blue-600 bg-blue-50 dark:bg-blue-950/20 dark:text-blue-400 border-blue-200/50 dark:border-blue-800/30";
      case "Scheduled": return "text-indigo-600 bg-indigo-50 dark:bg-indigo-950/20 dark:text-indigo-400 border-indigo-200/50 dark:border-indigo-800/30";
      case "Delayed": return "text-amber-600 bg-amber-50 dark:bg-amber-950/20 dark:text-amber-400 border-amber-200/50 dark:border-amber-800/30";
      case "Cancelled": return "text-rose-600 bg-rose-50 dark:bg-rose-950/20 dark:text-rose-400 border-rose-200/50 dark:border-rose-800/30";
      default: return "text-slate-600 bg-slate-50 dark:bg-slate-800 dark:text-slate-400";
    }
  };

  const getPriorityColor = (priority) => {
    switch (priority) {
      case "Critical": return "text-rose-600 bg-rose-50 dark:bg-rose-950/20 dark:text-rose-400";
      case "High": return "text-amber-600 bg-amber-50 dark:bg-amber-950/20 dark:text-amber-400";
      case "Medium": return "text-blue-600 bg-blue-50 dark:bg-blue-950/20 dark:text-blue-400";
      default: return "text-slate-600 bg-slate-100 dark:bg-slate-800 dark:text-slate-400";
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 15 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -15 }}
      transition={{ duration: 0.25 }}
      className="space-y-6"
    >
      {/* Header */}
      <div className="flex items-center gap-3">
        <button
          onClick={onBack}
          className="p-2 rounded-xl border border-slate-200 dark:border-slate-800 text-slate-500 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors cursor-pointer"
        >
          <ArrowLeft className="h-5 w-5" />
        </button>
        <div className="flex-1">
          <div className="flex items-center gap-2.5 flex-wrap">
            <h1 className="text-xl md:text-2xl font-extrabold text-slate-900 dark:text-white tracking-tight">
              Trip {trip.tripId}
            </h1>
            <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-semibold border ${getStatusColor(trip.status)}`}>
              {trip.status}
            </span>
            <span className={`inline-flex items-center px-2 py-0.5 rounded-md text-[11px] font-semibold ${getPriorityColor(trip.priority)}`}>
              {trip.priority}
            </span>
          </div>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
            {trip.source} ➔ {trip.destination} • {trip.distance.toLocaleString()} miles
          </p>
        </div>
      </div>

      {/* Route & Progress Card */}
      <div className="bg-white/75 dark:bg-slate-900/60 backdrop-blur-md border border-slate-200/60 dark:border-slate-800/40 p-5 rounded-2xl shadow-xs">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 mb-5">
          <div>
            <h3 className="text-sm font-bold text-slate-800 dark:text-slate-200">Route Progress</h3>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
              Live shipment tracking from origin to destination
            </p>
          </div>
          <div className="text-right">
            <span className="text-2xl font-extrabold text-slate-900 dark:text-white">{progress}%</span>
            <p className="text-[10px] text-slate-400 uppercase tracking-wider font-bold mt-0.5">Transit Complete</p>
          </div>
        </div>

        {/* Route Visual */}
        <div className="flex items-center gap-3 mb-4">
          <div className="flex-1">
            <div className="flex items-center justify-between mb-2">
              <div className="flex items-center gap-1.5 text-xs font-semibold text-slate-700 dark:text-slate-300">
                <div className="w-2.5 h-2.5 rounded-full bg-blue-500" />
                {trip.source}
              </div>
              <div className="flex items-center gap-1.5 text-xs font-semibold text-slate-700 dark:text-slate-300">
                {trip.destination}
                <div className="w-2.5 h-2.5 rounded-full bg-emerald-500" />
              </div>
            </div>
            <div className="h-3 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
              <motion.div
                initial={{ width: 0 }}
                animate={{ width: `${progress}%` }}
                transition={{ duration: 1.5, ease: "easeOut" }}
                className="h-full bg-gradient-to-r from-blue-500 via-indigo-500 to-emerald-500 rounded-full relative"
              >
                {progress > 0 && progress < 100 && (
                  <div className="absolute right-0 top-1/2 -translate-y-1/2 w-4 h-4 rounded-full bg-white dark:bg-slate-950 border-2 border-blue-500 shadow-sm" />
                )}
              </motion.div>
            </div>
            <div className="flex justify-between text-[10px] text-slate-400 mt-1.5 font-medium">
              <span>0 mi</span>
              <span>{trip.distance.toLocaleString()} mi</span>
            </div>
          </div>
        </div>

        {/* Trip Info Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 pt-4 border-t border-slate-100 dark:border-slate-800/50">
          <div className="text-center p-3 bg-slate-50/50 dark:bg-slate-900/20 rounded-xl border border-slate-100 dark:border-slate-800/50">
            <Clock className="h-4 w-4 mx-auto text-blue-500 mb-1" />
            <p className="text-[10px] text-slate-400 font-bold uppercase">Departed</p>
            <p className="text-xs font-bold text-slate-800 dark:text-slate-200 mt-0.5">
              {new Date(trip.startTime).toLocaleString("en-US", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" })}
            </p>
          </div>
          <div className="text-center p-3 bg-slate-50/50 dark:bg-slate-900/20 rounded-xl border border-slate-100 dark:border-slate-800/50">
            <Navigation className="h-4 w-4 mx-auto text-indigo-500 mb-1 rotate-45" />
            <p className="text-[10px] text-slate-400 font-bold uppercase">ETA</p>
            <p className="text-xs font-bold text-slate-800 dark:text-slate-200 mt-0.5">{trip.eta}</p>
          </div>
          <div className="text-center p-3 bg-slate-50/50 dark:bg-slate-900/20 rounded-xl border border-slate-100 dark:border-slate-800/50">
            <MapPin className="h-4 w-4 mx-auto text-emerald-500 mb-1" />
            <p className="text-[10px] text-slate-400 font-bold uppercase">Distance</p>
            <p className="text-xs font-bold text-slate-800 dark:text-slate-200 mt-0.5">{trip.distance.toLocaleString()} mi</p>
          </div>
          <div className="text-center p-3 bg-slate-50/50 dark:bg-slate-900/20 rounded-xl border border-slate-100 dark:border-slate-800/50">
            <Package className="h-4 w-4 mx-auto text-amber-500 mb-1" />
            <p className="text-[10px] text-slate-400 font-bold uppercase">Cargo</p>
            <p className="text-xs font-bold text-slate-800 dark:text-slate-200 mt-0.5">{trip.cargoType || "General"}</p>
          </div>
        </div>
      </div>

      {/* Content Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">

        {/* Left Column: Timeline */}
        <div className="lg:col-span-2 space-y-6">

          {/* Operations Timeline */}
          <div className="bg-white/75 dark:bg-slate-900/60 backdrop-blur-md border border-slate-200/60 dark:border-slate-800/40 p-5 rounded-2xl shadow-xs">
            <h3 className="text-sm font-bold text-slate-800 dark:text-slate-200 mb-5">Operations Timeline</h3>
            <div className="flow-root">
              <ul className="-mb-6">
                {timelineEvents.map((event, idx) => {
                  const Icon = event.icon;
                  return (
                    <li key={event.id}>
                      <div className="relative pb-6">
                        {idx !== timelineEvents.length - 1 && (
                          <span className="absolute top-4 left-4 -ml-px h-full w-0.5 bg-slate-150 dark:bg-slate-800/80" aria-hidden="true" />
                        )}
                        <div className="relative flex space-x-3 items-start">
                          <div>
                            <span className={`h-8 w-8 rounded-lg flex items-center justify-center ${getTimelineIcon(event.status)}`}>
                              <Icon className="h-4 w-4" />
                            </span>
                          </div>
                          <div className="flex-1 min-w-0 pt-0.5">
                            <div className="flex justify-between items-start gap-2">
                              <p className={`text-xs font-bold ${event.status === "pending" ? "text-slate-400 dark:text-slate-600" : "text-slate-800 dark:text-slate-200"}`}>
                                {event.label}
                              </p>
                              <span className={`text-[10px] whitespace-nowrap font-semibold ${event.status === "pending" ? "text-slate-350 dark:text-slate-600" : "text-slate-450 dark:text-slate-500"}`}>
                                {event.time}
                              </span>
                            </div>
                            <p className={`text-[11px] mt-0.5 leading-relaxed ${event.status === "pending" ? "text-slate-350 dark:text-slate-650" : "text-slate-500 dark:text-slate-400"}`}>
                              {event.detail}
                            </p>
                          </div>
                        </div>
                      </div>
                    </li>
                  );
                })}
              </ul>
            </div>
          </div>

          {/* Delivery Notes */}
          <div className="bg-white/75 dark:bg-slate-900/60 backdrop-blur-md border border-slate-200/60 dark:border-slate-800/40 p-5 rounded-2xl shadow-xs">
            <div className="flex items-center gap-2 mb-3">
              <FileText className="h-4 w-4 text-blue-500" />
              <h3 className="text-sm font-bold text-slate-800 dark:text-slate-200">Delivery Notes</h3>
            </div>
            <div className="p-3.5 bg-slate-50 dark:bg-slate-900/30 rounded-xl border border-slate-100 dark:border-slate-800/60 text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
              {trip.notes || "Handle with care. Call receiver 30 minutes before arrival. Unloading dock #4. Ensure temperature-controlled environment is maintained during transit. Driver must collect signed proof of delivery."}
            </div>
          </div>

          {/* Attached Documents */}
          <div className="bg-white/75 dark:bg-slate-900/60 backdrop-blur-md border border-slate-200/60 dark:border-slate-800/40 p-5 rounded-2xl shadow-xs">
            <div className="flex items-center gap-2 mb-3">
              <Paperclip className="h-4 w-4 text-blue-500" />
              <h3 className="text-sm font-bold text-slate-800 dark:text-slate-200">Attached Documents</h3>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {[
                { name: "Bill_of_Lading.pdf", size: "245 KB", type: "PDF" },
                { name: "Cargo_Manifest.pdf", size: "128 KB", type: "PDF" },
                { name: "Insurance_Certificate.pdf", size: "312 KB", type: "PDF" },
              ].map((doc, idx) => (
                <div key={idx} className="flex items-center gap-3 p-3 bg-slate-50 dark:bg-slate-900/25 rounded-xl border border-slate-100 dark:border-slate-800/50 hover:border-slate-300 dark:hover:border-slate-700 transition-colors cursor-pointer group">
                  <div className="p-2 bg-rose-50 dark:bg-rose-950/20 text-rose-500 rounded-lg flex-shrink-0">
                    <FileText className="h-4 w-4" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-xs font-semibold text-slate-700 dark:text-slate-300 truncate group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors">{doc.name}</p>
                    <p className="text-[10px] text-slate-400">{doc.size} • {doc.type}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Right Column: Driver, Vehicle, Fuel */}
        <div className="space-y-6">

          {/* Driver Card */}
          <div className="bg-white/75 dark:bg-slate-900/60 backdrop-blur-md border border-slate-200/60 dark:border-slate-800/40 p-5 rounded-2xl shadow-xs">
            <div className="flex items-center gap-2 mb-4">
              <User className="h-4 w-4 text-blue-500" />
              <h3 className="text-sm font-bold text-slate-800 dark:text-slate-200">Assigned Driver</h3>
            </div>
            <div className="flex items-center gap-3.5">
              <div className="relative flex-shrink-0">
                <div className="w-12 h-12 rounded-xl bg-gradient-to-tr from-blue-600 to-indigo-500 text-white flex items-center justify-center font-bold text-sm shadow-md">
                  {trip.driver.split(" ").map(w => w[0]).join("")}
                </div>
                <span className="absolute -bottom-0.5 -right-0.5 block h-3 w-3 rounded-full bg-emerald-500 ring-2 ring-white dark:ring-slate-900" />
              </div>
              <div>
                <p className="text-sm font-bold text-slate-800 dark:text-slate-200">{trip.driver}</p>
                <p className="text-[11px] text-slate-500 dark:text-slate-450">CDL Class A • 4.8★ Rating</p>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-2 mt-4">
              <div className="p-2.5 bg-slate-50/50 dark:bg-slate-900/20 rounded-lg border border-slate-100 dark:border-slate-800/50 text-center">
                <p className="text-[10px] text-slate-400 font-bold uppercase">Experience</p>
                <p className="text-xs font-bold text-slate-700 dark:text-slate-300 mt-0.5">6 Years</p>
              </div>
              <div className="p-2.5 bg-slate-50/50 dark:bg-slate-900/20 rounded-lg border border-slate-100 dark:border-slate-800/50 text-center">
                <p className="text-[10px] text-slate-400 font-bold uppercase">Total Trips</p>
                <p className="text-xs font-bold text-slate-700 dark:text-slate-300 mt-0.5">287</p>
              </div>
            </div>
          </div>

          {/* Vehicle Card */}
          <div className="bg-white/75 dark:bg-slate-900/60 backdrop-blur-md border border-slate-200/60 dark:border-slate-800/40 p-5 rounded-2xl shadow-xs">
            <div className="flex items-center gap-2 mb-4">
              <Truck className="h-4 w-4 text-blue-500" />
              <h3 className="text-sm font-bold text-slate-800 dark:text-slate-200">Assigned Vehicle</h3>
            </div>
            <div className="w-full h-28 rounded-xl bg-gradient-to-tr from-indigo-600 via-blue-600 to-blue-800 flex items-center justify-center relative overflow-hidden mb-4">
              <div className="absolute inset-0 opacity-10 bg-[radial-gradient(#fff_1px,transparent_1px)] [background-size:16px_16px]" />
              <Truck className="w-12 h-12 text-white/90" />
            </div>
            <p className="text-sm font-bold text-slate-800 dark:text-slate-200">{trip.vehicle}</p>
            <div className="grid grid-cols-2 gap-2 mt-3">
              <div className="p-2 bg-slate-50/50 dark:bg-slate-900/20 rounded-lg border border-slate-100 dark:border-slate-800/50 text-center">
                <p className="text-[10px] text-slate-400 font-bold uppercase">Type</p>
                <p className="text-[11px] font-bold text-slate-700 dark:text-slate-300 mt-0.5">Heavy Truck</p>
              </div>
              <div className="p-2 bg-slate-50/50 dark:bg-slate-900/20 rounded-lg border border-slate-100 dark:border-slate-800/50 text-center">
                <p className="text-[10px] text-slate-400 font-bold uppercase">Capacity</p>
                <p className="text-[11px] font-bold text-slate-700 dark:text-slate-300 mt-0.5">40,000 lbs</p>
              </div>
            </div>
          </div>

          {/* Fuel Estimate Card */}
          <div className="bg-white/75 dark:bg-slate-900/60 backdrop-blur-md border border-slate-200/60 dark:border-slate-800/40 p-5 rounded-2xl shadow-xs">
            <div className="flex items-center gap-2 mb-4">
              <Fuel className="h-4 w-4 text-rose-500" />
              <h3 className="text-sm font-bold text-slate-800 dark:text-slate-200">Estimated Fuel</h3>
            </div>
            <div className="space-y-3">
              <div className="flex justify-between items-center text-sm">
                <span className="text-slate-500 dark:text-slate-450">Avg. Efficiency</span>
                <span className="font-bold text-slate-800 dark:text-slate-200">{fuelEstimate.rate}</span>
              </div>
              <div className="flex justify-between items-center text-sm border-t border-slate-100 dark:border-slate-800/50 pt-2.5">
                <span className="text-slate-500 dark:text-slate-450">Est. Consumption</span>
                <span className="font-bold text-slate-800 dark:text-slate-200">{fuelEstimate.estimated} Gal</span>
              </div>
              <div className="flex justify-between items-center text-sm border-t border-slate-100 dark:border-slate-800/50 pt-2.5">
                <span className="text-slate-500 dark:text-slate-450">Est. Cost</span>
                <span className="font-bold text-rose-600 dark:text-rose-400">${fuelEstimate.cost.toLocaleString()}</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </motion.div>
  );
}
